export enum weatherIcons {
  SNOW = 'snow',
  SNOW_SHOWERS_DAY = 'snow-showers-day',
  SNOW_SHOWERS_NIGHT = 'snow-showers-night',
  RAIN = 'rain',
  THUNDER_RAIN = 'thunder-rain',
  THUNDER_SHOWERS_DAY = 'thunder-showers-day',
  THUNDER_SHOWERS_NIGHT = 'thunder-showers-night',
  SHOWERS_DAY = 'showers-day',
  SHOWERS_NIGHT = 'showers-night',
  FOG = 'fog',
  WIND = 'wind',
  CLOUDY = 'cloudy',
  PARTLY_CLOUDY_DAY = 'partly-cloudy-day',
  PARTLY_CLOUDY_NIGHT = 'partly-cloudy-night',
  CLEAR_DAY = 'clear-day',
  CLEAR_NIGHT = 'clear-night',
}
